import type { Message } from './model';

export const MESSAGES: ReadonlyArray<Message> = [
  {
    id: 'm-1',
    from: 'Ada Lovelace',
    subject: 'Re: Q2 ramp plan',
    preview: 'Sharing the engineering capacity by team for the upcoming quarter…',
    body: 'Hi team,\n\nSharing the engineering capacity by team for the upcoming quarter. Headcount allocations are tentative until we close the open roles in security and platform.\n\nLet me know if anything looks off.\n\nAda',
    unread: true,
    starred: false,
    receivedAt: '10:42',
  },
  {
    id: 'm-2',
    from: 'Grace Hopper',
    subject: 'Compiler review on Friday',
    preview: 'Lining up the agenda. Want to walk through the bytecode-cache patch first…',
    body: 'Hi all,\n\nLining up the agenda. Want to walk through the bytecode-cache patch first; cherry-picked the diff into the review branch.\n\nGrace',
    unread: true,
    starred: true,
    receivedAt: '09:18',
  },
  {
    id: 'm-3',
    from: 'Linus Torvalds',
    subject: 'kernel ci is flaky again',
    preview: 'Dropping the run logs here — looks like the same race we saw last month…',
    body: 'kernel ci is flaky again — same race condition we saw last month. logs attached.',
    unread: false,
    starred: false,
    receivedAt: 'Yesterday',
  },
  {
    id: 'm-4',
    from: 'Margaret Hamilton',
    subject: 'Apollo postmortem draft',
    preview: 'Initial draft attached for review. Two open questions about the timing analysis…',
    body: 'Initial draft attached. Two open questions about the timing analysis — I can pull more telemetry if needed.',
    unread: false,
    starred: true,
    receivedAt: 'Yesterday',
  },
  {
    id: 'm-5',
    from: 'Donald Knuth',
    subject: 'TAOCP volume 4B feedback',
    preview: 'Thank you for the careful read. Most of the suggestions match my own marginalia…',
    body: 'Thank you for the careful read. Most of the suggestions match my own marginalia. I will integrate the corrections in the next pass.',
    unread: false,
    starred: false,
    receivedAt: 'Mon',
  },
  {
    id: 'm-6',
    from: 'Barbara Liskov',
    subject: 'CLU type-system question',
    preview: 'Following up on the parametric polymorphism discussion from the workshop…',
    body: 'Following up on the parametric polymorphism discussion from the workshop. Sending a small write-up next week.',
    unread: false,
    starred: false,
    receivedAt: 'Mon',
  },
];
