import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

/*
 * MSW Service Worker for the dev server. Activated only when
 * VITE_USE_MSW=true (see src/main.tsx). Tests use ./node.ts instead.
 *
 * The worker script lives at /mockServiceWorker.js (generated by
 * `pnpm dlx msw init public/`). Do not commit that file behind a build —
 * MSW expects it on the public root in dev.
 */

export const worker = setupWorker(...handlers);
